### ISSUE TITLE
Run on Companion Computer

### ISSUE THREAD

**Issue by natetoombs** [danzimmerman/barebones_MAVLink#2]
I'm trying to get this code running on a companion computer instead of using a microcontroller. I'm using a custom drone autopilot that doesn't use mavlink, so I also want to generate mavlink messages to send to QGC.

Any tips for adapting the code to run on a computer? Right now, my problem is that the Serial library is arduino-specific, but I want something like that to send and receive messages from QGC.

**Comment by danzimmerman** [comment]
What kind of computer and what kind of link between the companion and the ground station? Serial telemetry radio?

The serial port is probably going to be a bit tied to the specific hardware especially in C/C++ code, but there are probably be some kind of I/O libraries that will help you with serial comms. For a Raspberry Pi I think WiringPi would work:

http://wiringpi.com/reference/serial-library

Might be convenient to skip the C/C++ and look at some of the MAVLink developer tools with Python APIs. 

Dronekit seems to be a high level API for doing stuff with MAVLink messaging:

https://dronekit.netlify.app/

And I think that relies on pymavlink libraries:

https://mavlink.io/en/mavgen_python/
https://github.com/ArduPilot/pymavlink/blob/master/examples/mavtest.py

I haven't really used either (aside from the mavgen functionality in pymavlink) so can't be of much specific help, but suspect you can write a Python program that pretty much mimics this Arduino code.

**Comment by danzimmerman** [comment]
This might be a useful resource for C programming with a serial port in Linux:

https://blog.mbedded.ninja/programming/operating-systems/linux/linux-serial-ports-using-c-cpp/#basic-setup-in-c

**Comment by natetoombs** [comment]
Sorry about the late response, and thanks for the resources! My biggest problem has been using the pymavlink library to fake a generic autopilot like you have, sending heartbeat messages alone doesn't seem to be working for me. This is unrelated to your project, so I'll close with this comment, but if you have any further tips they would be appreciated. Thanks!
